package cnss.models;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity Assure composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 *
 * @author 
 */
@Entity
@Table(name = "Assurecnss")
public class Assure implements Serializable {
   
  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each Assure in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The Assure's email
  @NotNull
  private String email;
  
  // The Assure's name
  @NotNull
  private String name;
  
  @NotNull
  private String pays;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Assure() { }

  public Assure(long id) { 
    this.id = id;
  }
  
  public Assure(String email, String name) {
    this.email = email;
    this.name = name;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String value) {
    this.email = value;
  }
  
  public String getName() {
    return name;
  }

  public void setName(String value) {
    this.name = value;
  }

@Override
public String toString() {
	return "Assure [name=" + name + ", pays=" + pays + "]";
}
  
} // class Assure
